services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file: .env
    ports:
      - "1434:1433"

  web-segura:
    build: .
    ports:
      - "5001:5001"
    env_file: .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
